branch-defaults:
  master:
    environment: Custom-env
global:
  application_name: OdecoPack
  default_ec2_keyname: odecossh
  default_platform: 64bit Amazon Linux 2016.09 v2.2.0 running Python 3.4
  default_region: us-west-2
  profile: eb-cli
  sc: git
