branch-defaults:
  master:
    environment: Custom-env
global:
  application_name: OdecoPack
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: us-west-2
  profile: odecopack
  sc: git
